// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type File struct {
	ID          int64          `json:"id"`
	OwnerID     int64          `json:"owner_id"`
	FileName    string         `json:"file_name"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Coordinates sql.NullString `json:"coordinates"`
}

type User struct {
	ID       int64          `json:"id"`
	Login    string         `json:"login"`
	Password string         `json:"password"`
	Email    sql.NullString `json:"email"`
	IsAdmin  int64          `json:"is_admin"`
}
