// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"server/types"
)

type Album struct {
	ID      int64                `json:"id"`
	OwnerID int64                `json:"owner_id"`
	CoverID types.JSONNullInt64  `json:"cover_id"`
	Title   types.JSONNullString `json:"title"`
}

type File struct {
	ID          int64                `json:"id"`
	OwnerID     int64                `json:"owner_id"`
	FileName    string               `json:"file_name"`
	Title       types.JSONNullString `json:"title"`
	Description types.JSONNullString `json:"description"`
	Coordinates types.JSONNullString `json:"coordinates"`
	Checksum    string               `json:"checksum"`
	CreatedAt   types.JSONNullTime   `json:"created_at"`
}

type Filealbum struct {
	FileID  int64 `json:"file_id"`
	AlbumID int64 `json:"album_id"`
}

type Fileguestshare struct {
	ID        int64               `json:"id"`
	FileID    int64               `json:"file_id"`
	Url       string              `json:"url"`
	CreatedAt types.JSONNullTime  `json:"created_at"`
	ExpiresAt types.JSONNullTime  `json:"expires_at"`
	MaxUses   types.JSONNullInt64 `json:"max_uses"`
}

type Filetag struct {
	FileID int64 `json:"file_id"`
	TagID  int64 `json:"tag_id"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID       int64                `json:"id"`
	Login    string               `json:"login"`
	Password string               `json:"password"`
	Email    types.JSONNullString `json:"email"`
	Profile  types.JSONNullString `json:"profile"`
	IsAdmin  int64                `json:"is_admin"`
}
